project:
  type: book

book:
  title: "IES Statistical Practicals"
  author: "Fred Ho"
  date: "29/07/2026"
  chapters:
    - index.qmd
    - chapters/p1.qmd
    - chapters/p2.qmd
    - chapters/w1-practical.qmd
    - chapters/w2-practical.qmd
    - chapters/w3-practical.qmd
    - chapters/w4-practical.qmd
    - chapters/w5-practical.qmd

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



