project:
  type: book

book:
  title: "IES Statistical Practicals"
  author: "Fred Ho"
  date: "29/07/2026"
  chapters:
    - index.qmd
    - chapters/05-prep1.qmd
    - chapters/06-prep2.qmd
    - chapters/07-descriptive.qmd
    - chapters/08-estimation.qmd
    - chapters/09-comparison.qmd
    - chapters/10-regression.qmd
    - chapters/11-adjustment.qmd

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



